name: TypeScript Deployment Workflow

on:
  push:
    branches:
      - ts-main

jobs:
  setup-and-test:

    uses: seminho77/WebEngineering/.github/workflows/setup-and-test.yml@ts-main

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: setup-and-test

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
