name: TypeScript Deployment Workflow

on:
  push:
    branches:
      - ts-main

jobs:
  build-and-deploy:
    needs: setup-test  # Waiting for finish of reusable workflow
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup, Lint, and Test
        uses: ./.github/workflows/setup-and-test.yml  # Calling reusable workflow

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true