name: TypeScript Deployment Workflow

on:
  push:
    branches:
      - ts-main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Reusing setup, lint, and test steps from the reusable workflow
      - name: Setup, Lint, and Test
        uses: seminho77/WebEngineering/.github/workflows/setup-and-test.yml@ts_dev
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
